version: '3.8'

services:
  geth:
    image: "${DOCKER_HUB_USERNAME}/go-ethereum:latest"
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
    command: --dev --http --http.addr 0.0.0.0
    volumes:
      - geth-data:/root/.ethereum

volumes:
  geth-data:
