apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      containers:
      - name: blockscout
        image: blockscout/blockscout:latest
        ports:
        - containerPort: 4000
