apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout
  template:
    metadata:
      labels:
        app: blockscout
    spec:
      containers:
      - name: blockscout
        image: blockscout/blockscout:latest
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "0.5"
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgresql-service:5432/$(POSTGRES_DB)"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: SECRET_KEY_BASE
        - name: ETHEREUM_JSONRPC_HTTP_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: ETHEREUM_JSONRPC_HTTP_URL
