apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ethereum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-ethereum
  template:
    metadata:
      labels:
        app: go-ethereum
    spec:
      containers:
      - name: go-ethereum
        image: nikolaivanovj/go-ethereum:latest
        ports:
        - containerPort: 8545
        - containerPort: 8546
        - containerPort: 30303
        - containerPort: 30303
