apiVersion: v1
kind: Service
metadata:
  name: go-ethereum-service
spec:
  selector:
    app: go-ethereum
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 8545
    targetPort: 8545
  type: LoadBalancer

