name: Deploy to AKS

on:
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  build_and_push:
    if: github.event.label.name == 'CICD'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build and Push Docker Image
      run: |
        docker buildx build --push --tag nikolaivanovj/go-ethereum:latest .

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubernetes tools
      run: |
        sudo snap install kubectl --classic

    - name: Configure kubectl
      env:
        DOSPN_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        DOSPN_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        DOSPN_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
        DOSPN_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
      run: |
        az login --service-principal --username $DOSPN_CLIENT_ID --password $DOSPN_CLIENT_SECRET --tenant $DOSPN_TENANT_ID
        az aks get-credentials --resource-group gethdevnetrg --name gethdevnetaks

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/blockscout.yaml
