name: Deploy Existing Docker Image to AKS

on:
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  deploy:
    if: github.event.label.name == 'CD:DeployToAKS'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubernetes tools
      run: |
        sudo snap install kubectl --classic

    - name: Configure kubectl
      env:
        DOSPN_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        DOSPN_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        DOSPN_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
        DOSPN_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
      run: |
        az login --service-principal --username $DOSPN_CLIENT_ID --password $DOSPN_CLIENT_SECRET --tenant $DOSPN_TENANT_ID
        az aks get-credentials --resource-group gethdevnetrg --name gethdevnetaks

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/blockscout.yaml
        kubectl apply -f k8s/blockscout-service.yaml
