name: Terraform Apply

on:
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  terraform:
    if: github.event.label.name == 'CI:Terraform-Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Verify Environment Variables
      env:
        DOSPN_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        DOSPN_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        DOSPN_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
        DOSPN_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
      run: |
        if [ -z "$DOSPN_CLIENT_ID" ]; then echo "DOSPN_CLIENT_ID is not set"; exit 1; fi
        if [ -z "$DOSPN_CLIENT_SECRET" ]; then echo "DOSPN_CLIENT_SECRET is not set"; exit 1; fi
        if [ -z "$DOSPN_TENANT_ID" ]; then echo "DOSPN_TENANT_ID is not set"; exit 1; fi
        if [ -z "$DOSPN_SUBSCRIPTION_ID" ]; then echo "DOSPN_SUBSCRIPTION_ID is not set"; exit 1; fi

    - name: Terraform Init
      env:
        ARM_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
      run: terraform -chdir=terraform init -input=false -no-color

    - name: Terraform Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
        TF_VAR_client_id: ${{ secrets.DOSPN_CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.DOSPN_CLIENT_SECRET }}
        TF_VAR_subscription_id: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
        TF_VAR_tenant_id: ${{ secrets.DOSPN_TENANT_ID }}
      run: terraform -chdir=terraform apply -auto-approve
