name: Terraform Plan

on:
  pull_request:
    branches:
      - master
    types:
      - labeled

jobs:
  terraform:
    if: github.event.label.name == 'CI:Terraform-Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Login to Azure CLI
      env:
        DOSPN_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        DOSPN_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        DOSPN_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}
      run: |
        az login --service-principal --username $DOSPN_CLIENT_ID --password $DOSPN_CLIENT_SECRET --tenant $DOSPN_TENANT_ID

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}

    - name: Terraform Plan
      run: terraform plan -var "client_id=$DOSPN_CLIENT_ID" -var "client_secret=$DOSPN_CLIENT_SECRET" -var "subscription_id=$DOSPN_SUBSCRIPTION_ID" -var "tenant_id=$DOSPN_TENANT_ID" -out=tfplan
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.DOSPN_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.DOSPN_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.DOSPN_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.DOSPN_TENANT_ID }}

    - name: Show Plan (Hiding Sensitive Information)
      run: terraform show -json tfplan | jq 'del(.planned_values.root_module.resources[] | select(.type == "azurerm_kubernetes_cluster") | .values.kube_config_raw)'
      working-directory: ./terraform
